[book]
title = "笔记本📓"
authors = ["xsaxl","龙Tory"]
language = "ch"


[preprocessor.index]


[output.html.fold]
enable = true
# 折叠等级，为1时，只会将1级标题的内容展开。为x时，将x+1的所有级标题的内容展开。
level = 1

[output.html]
default-theme = "Rust"

[build]
# 监听被 .gitignore 忽略的章节文件（路径相对于 book.toml）
extra-watch-dirs = ["src/shit"]
# 或监听整个目录
# extra-watch-dirs = ["src/private"]